travis:
  secure:
    BINSTAR_TOKEN: BhP0TT1DdaU9u6aQWgSagBdZPpidLTW0e9xMIIkyWnzDHGposDuWcXQ/c/RQbOA0YqxHXhCNxIpKJ8m2Assl1xt2OD4BhEHnKCpZ+2G88VEgfHS+sd5M5uF1Ni9cZckfnQ5Ul9tAK3gg6rbXdh61zUSpqp1+CCS2NMECg+g9V2MV0sH1Wquf3k44HiFJl/VaMF21nNRFxCFgYzHddk04ZAa0y5nZYIbZzSzICF8zBoqMke+S9BzjDFv7XU2oeG9V+mepNtAkPVaA2PKD5rpGp65KcncJceicBT43T93qQtgiaGuh/LdjbxVVN1c7ChEAW3x0IFFg2Tyx/j5le8RBi/5lesajurLxQ5bZxR3ISzTzW/LeqMvzGIdkqzxEBH+HstHH9//mtpPdUiIAhWmpxN/FnM3F4+U0F+F+CALyMDoP11apfRzR/hnhHmv5Jd9di4Qs/PmbZ+Peisf92ZZp3L3MxNiWLodCmLQcymnkxoWWmsb30g38wNXMa2m7A3TX7lzvA/qYcMwQVs4h/Ev9hw6rLzO39Q0sK/MW0IMZpa2IlY0MfzGrVz4sC9Z1ub6Z1Ve8xZXn+3UW0Hr240Fg4qVkm3q7iluW03OEBCZmH6Ay4c8PzFSIrQxE+NXYsV35KJuP13xPlkeAyrdSwG3YcT08qEKvSKZRCp4VQMzKTlI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
