travis:
  secure:
    BINSTAR_TOKEN: uCrkQSKl28aj6n6oN0mXE50zH7ZcJVKxqJB4IT2zdpVfU59cBtu1TuGBMA+NOgLKjnGd16whpaqy84lgPxpMtSQXKdjSPrmGVRs8Qz6eui3wMzN3jo7ixLEL2bhrdBJRFBvbvjtJ2RCCDFBpZMLxT4ClxsyiJk9NFY3HuZd5Ekf6nOT1ibzhH3v/3gpmr6ovQNb2YwVtYG2x5JLEDpNdW6j4YMqfHg07i0X4wzc+L2LpVKOLXetoNK6tlEe/G/jsB+i2sdnZZpHAvxF1vyZVeFPtun8WqlKixYdmTgCBvngstFY4Ke6dtNqyi11lfTP7S8VVjNlFYS2BFR1iAnccEyfoRxOeRKBa/OnhhunZ8pmrt285NxNDmNClg9gPHnKnRrD9mBaJ8mreI8f4S0ce7e9Hi/ZE2tAvzE+CJYdp2jRGdLdR6+L3NEgHhlkPWuQOK/pBqYqVD9POBGZlVCAQ7ukizcdgX0nPDldQOWRO82xwqe/FjjmsJlYnQH335VJ2tYMWiC5SZ4dw338+r6OnhoUP9SGbZVduSeLe/5C4fvqxcySm7ZHUJUmU4mT8bgCcQpGZDfcMtrozGoPiZHwANo/l2ix8w/qffn1yrCXgsSjRZpugSI9l/4xri3Y6wLsCyqh3rAYzcCEiw20K2QFvrIYSq7Xlyp5SiVg4JPQejP8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
